services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=8080
      - GRPC_HOST=0.0.0.0
      - GRPC_PORT=50051
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=auction_user
      - DB_PASSWORD=auction_password
      - DB_NAME=auction_db
      - DB_SSLMODE=disable
    networks:
      - auction-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=auction_user
      - POSTGRES_PASSWORD=auction_password
      - POSTGRES_DB=auction_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auction_user -d auction_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auction-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - auction-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  auction-network:
    driver: bridge

volumes:
  postgres_data:
